### PR TITLE
Fix spaces in paths and validating arguments

### LINKED ISSUE #135: The ruleset file does not exist error
I upgraded to the latest version and I got the error:
```
SyntaxError: Unexpected token 'E', "ERROR: The"... is not valid JSON
["ERROR" - 9:57:44 AM] ERROR: The file "Sites/dev/app/public/wp-content/plugins/example/phpcs.xml" does not exist.
```

There is a space in my project path. The full path is: `/home/dani/Local Sites/dev/app/public/wp-content/plugins/example/phpcs.xml`

Vscode version: **1.92.2**
OS: **Fedora 40**
Local dev env: **Local by FlyWheel**
Extension version: **0.0.19**

### PR DESCRIPTION
**Pull request by yCodeTech**
Fixes #135, and it's sub-issues #158 and #162.

In order to begin fixing the long-standing issue of spaces in paths and general escaping, we first need to deal with the unmaintained package `cross-spawn`. There are multiple open issues and pull requests, some from years ago. Some issues are relating to security and other flaws. So it's best to remove the dependency. Plus only fixer is using cross-spawn anyway (sniffer uses Node's `spawn` directly.

Another reason to remove the package is because in Node v24.x, passing the arguments array to `spawn` (or `execFile`) with `shell` option `true` is **deprecated** (ref: https://github.com/nodejs/node/pull/57199). There is an open issue in cross-spawn from August (https://github.com/moxystudio/node-cross-spawn/issues/176), but probably won't be fixed. So we will need to do our own fix anyway.

---

~For the escaping side of things, we could take some of the [code from cross-spawn](https://github.com/moxystudio/node-cross-spawn/blob/master/lib/util/escape.js) and implement it directly. Using `shell: true` negates cross-spawn's escaping anyway, so by taking some of it's code we can escape the command and arguments ourselves.~ No longer applicable since input validation works better.

Also because `shell: true` also doesn't allow Node to throw it's `ENOENT` error, and cross-spawn seems to [re-add this error back](https://github.com/moxystudio/node-cross-spawn/blob/master/lib/enoent.js), we can take some of that code and implement it directly too.

### CODE REVIEW

File: src/fixer.ts [hunk 1]
```diff
@@ -1,5 +1,4 @@
-import spawn from 'cross-spawn';
-import { SpawnSyncOptions } from 'node:child_process';
+import { spawnSync, SpawnSyncOptions } from 'node:child_process';
```
Comment (valeryan) [inline src/fixer.ts:1]: Have you tested that this works on windows? The reason we used cross spawn was because it handled windows better. It's been years so it might not be the case that windows sometimes barfs on spawn so I just want to know that you verified that it no longer needed.

**Review by valeryan — APPROVED** [review]

File: src/fixer.ts (hunk 1 above)
Comment (valeryan) [reply src/fixer.ts:1]: Lets make a task maybe to evaluate https://www.npmjs.com/package/execa as a possible replacement for cross-spawn. It is apparently the spiritual successor but I have no history with it.

Comment (yCodeTech) [reply src/fixer.ts:1]: I have researched Execa prior to opening this PR.

The thing is with Execa is that it also relies on cross-spawn under the hood. There is an [open issue] (https://github.com/sindresorhus/execa/issues/578) to remove cross-spawn, and has some really detailed feature breakdown of what cross-spawn does and possible plans to replicate those features in the package. It also has some good arguments to get rid of cross-spawn. But currently it hasn't made any progress to remove cross-spawn.

This issue on Execa is what prompted me to drop cross-spawn here and implement the features/fixes ourselves.

Comment (valeryan) [reply src/fixer.ts:1]: It sounds like you have been very thorough, thanks.

**Comment by yCodeTech** [comment]
Escaping special characters is all well and good to prevent command injection, but we should also be validating the user-supplied arguments to ensure only PHPCS/CBF arguments can be used, and not random commands. This will help considerably when it comes to preventing command injections such as:

```json
"phpsab.snifferArguments": [
  "\" - > nul 2>&1 & whoami & echo %USERPROFILE% & echo done;"
],
```

We should also only support a limited subset of the arguments since there's only a few that are relevant to our usages.

The arguments (other than the internally used `--standard`, `--stdin-path`, `--report`, `-q` , and `-`) I propose to support are:

- `--filter` 
- `--ignore`
- `--severity`
- `--error-severity`
- `--warning-severity`
- `--ignore-annotations`

**Comment by yCodeTech** [comment]
@valeryan I'm just chipping away at this slowly. I've been ill recently, so that's why progress has been slow. But it's nearly done I think. I should be able to merge it soon. Get tests done, and push out a release by end of the month all being well.

**Comment by yCodeTech** [comment]
Now with the new input validation we don't actually need to escape any characters. Escaping characters is very error prone as it is, especially between all the different systems. Input validation is the safer way to go, plus limiting the arguments to a specific whitelist, and validating the values will go a long way to protect against malformed and malicious commands.

The notion of escaping characters is now scrapped.

**Comment by jonathanbossenger** [comment]
I will do my best to give this a test this week.

**Comment by yCodeTech** [comment]
@jonathanbossenger Have you had chance to test this PR?
